### ISSUE TITLE
SPI speed limitation to 7.8 MHz

### ISSUE THREAD

**Issue by maxscheel** [tmolteno/TART#2]
Papillio Pro <-> RPi SPI speed limited to 7.8 MHz.
Faster speeds will cause issues as the Papillio latches to the sclk provided by the RPI. 96 MHz is too slow to latch to rising and falling edge. SPI client needs a make over.

**Comment by tmolteno** [comment]
Now being worked on.  SPI rewrite in progress by @patsuggate

**Comment by psuggate** [comment]
Hey Tim,

How'd ya do that?
