### ISSUE TITLE
colour selection for vis imaging only works on localhost

### ISSUE THREAD

**Issue by milletf1** [tmolteno/TART#22]
Not sure why this is, will try fix tomorrow.

**Comment by milletf1** [comment]
This issue is being caused when the save-pixels package is given an array of  coloured pixels in production builds.  I'll debug this at a later date.

**Comment by maxscheel** [comment]
lets just use our own colouring. i updated the api_synthesis package to only depend on colormap (with viridis support) and removed dep to apply_colormap (not maintained.)

providing "viridis" now working.
