### ISSUE TITLE
external paths still exist in web api

### ISSUE THREAD

**Issue by maxscheel** [tmolteno/TART#35]
currently requires (hardcoded) folder called 24_ant_setup with:
a) telescope_config.json 
b) calibrated_antenna_positions.json
this is also the path where the gains.db sqlite data base is stored. 

changes need to made in:
tart_web_api/config.py
tart_web_api/database.py

make sure that api can be installed and run by just 2 steps.
1) sudo pip install tart_web_api
2) LOGIN_PW=foobar FLASK_APP=tart_web_api flask run

**Comment by tmolteno** [comment]
This has been fixed (to some extent) in the recent containerised web_api. Persistence is still being worked on.

**Comment by tmolteno** [comment]
Closed as the API is now containerised
