### ISSUE TITLE
Web-App Enhancements

### ISSUE THREAD

**Issue by tmolteno** [tmolteno/TART#5]
Checklist of minor enhancements for the Web-GUI [https://tart.elec.ac.nz](url)

- [x] Add version number to bottom
- [x] Fix API documentation link
- [x] Add meta-information to the image view pane (date, number of baselines, integration time e.t.c)
- [x] Add telescope information to the landing page (location, number of antennas e.t.c) 
- [x] Add a loading screen
- [x] Change title to "Radio Telescope Console" from TartApp

**Comment by milletf1** [comment]
I have managed to get the API link to serve up api documentation.  However, it is setting the browser address to localhost/doc/.  I think this is caused by the nginx config because the response headers are returning Location: "http://localhost/doc/".

**Comment by tmolteno** [comment]
Closing, as these have been largely done. Any refinement and we'll create a new issue.
