### ISSUE TITLE
Spectrum View

### ISSUE THREAD

**Issue by tmolteno** [tmolteno/TART#6]
Needs to acquire raw data, will be very slow via the API.

**Comment by tmolteno** [comment]
Can downscale so the FFT is faster.

**Comment by maxscheel** [comment]
API now returns two additional keys 'freq' and 'power'
http://tart2-raspberry/api/v1/status/channel/0
http://tart2-raspberry/api/v1/status/channel
display power(y) vs freq(x) with perhaps:
http://www.chartjs.org/samples/latest/charts/scatter/basic.html
